BHoM/BHoM_UI

- BHoM_UI/Components/Engine/Explode.cs
Fixes #50.
You can try the file provide by Rob on this issue: https://github.com/BHoM/Grasshopper_Toolkit/issues/302
Just add a property to the CustomObject and the Explode should just turn orange instead of messing things up.
> BHoM_UI - Issue 50 - make sure the explode component don't update on empty input

- BHoM_UI/BHoM_UI.csproj
- BHoM_UI/Templates/Caller.cs
- BHoM_UI/Templates/ISelectorMenu.cs
- BHoM_UI/Templates/Selector.cs
- BHoM_UI/Templates/SelectorMenu.cs
- UI_PostBuild/Program.cs
Fixes #54.
Should enable contextual menu support in Excel that apparently doesn't expose WinForm or WPF directly.
No change needed in Grasshopper or Dynamo. I have kept the methods supporting directly WinForm and WPF since they will be the most common ones anyway so the user still gets a type strong interface for the general cases.
The overall architecture is admittedly a bit convoluted but this is necessary to keep type strong support all the way (nicer for things like OrganiseItems methods) while having a asynchronous discovery of the types for components items (needs to be done ahead of time to prevent lag on opening context menu) and menu type (only known when actually opening the menu).  I'll eventually review it when I have more time but this is doing the job for now.
@epignatelli , …
> BHoM_UI - Provide support for menus other than WinForm and WPF

- BHoM_UI/Components/Engine/Explode.cs
Fixes #63 
The property was registered with the general type `object`. For collection types, this caused the `DataAccessor` to ask for items rather lists.
This pr is storing the specific type.
You can test it together with https://github.com/BHoM/Grasshopper_Toolkit/pull/317 with this file:
https://burohappold.sharepoint.com/:u:/s/BHoM/EQ0-nZ87JpZNmelkOgfPQa8BfEWJaFM3-4pCC1TUVLgxPA?e=YweP8k
> Issue 62 - Register correct type when exploding custom objects

- BHoM_UI/Components/Engine/GetProperty.cs
Getting runtime type of the collected property value rather than declared type (GetProperty returns `object`)
Closes #64
The component was setting the output type base on the return type of the `GetPropertyValue` method, which is `object`. This creates problem when the runtime type is a `System.Collection`, preventing the component from unravelling it.
We're now getting the runtime type of the output. If `null` we're bypassing it and setting the declare type.
https://burohappold.sharepoint.com/:f:/s/BHoM/Es3A0aBdb11DibWCl17DCPwBgb0wmqEE9acA4vi50b_OLQ?e=Wnx240
- `public bool GetPropertyCaller.SetOutputTypes(object result)`
- `public override object GetPropertyCaller.Run(object[] inputs)`
> BHoM_UI-Issue64-GetPropertyHandlingCollections

- BHoM_UI/Components/oM/CreateCustom.cs
Closes #77 
Fixing a null check. If `types` is `null` `types.Count` fails and crashes Dynamo.
Just open Dynamo and add a property to CustomObject
> BHoM_UI-Issue77-NullCheckFix

- BHoM_UI/Components/oM/CreateCustom.cs
Closes #80 
It supports the changes in the child PR: https://github.com/BHoM/Grasshopper_Toolkit/pull/329
It:
1. Adds support for modifying the `InputParams` in each implemented UI (e.g. Grasshopper).
2. Explicitly stores the `InputParams` and the `ForcedType` for (de)serialisation. It would be useful to serialise the entire `Caller` through json - @adecler is there a reason we're avoiding it beside storing the bare minimum? Is it to avoid breaking the (de)ser of the components in case we change something at a lower level?
`public bool UpdateInput(int index, string name, Type type = null)`
`public bool RemoveInput(string name)`
`public bool UpdateInput(int index, string name, Type type = null)`
`public override string Write()`
`public override bool Read(string json)`
> BHoM_UI: Provide a way to update the InputParams in CustomObject

- BHoM_UI/Components/Engine/Explode.cs
Closes #74 
For `CustomObject`, this PR adds the base `BHoMObject` properties to the list of fields captured in the explode.
It adds them only if they are defined.
https://burohappold.sharepoint.com/:f:/s/BHoM/Egdx6sfWpplHnkdPH1R9EscBKtUpuoff95_8dXXabETf8g?e=avojRp
> Issue74-ExplodeCustomBaseProps

- BHoM_UI/Components/Adapter/Pull.cs
Closes #83 
Removes the part of the description that explicitly says that a "Pull all" behaviour is triggered when no query is used, since it is true only for specific adapters (Socket).
> #Fixes #83

- BHoM_UI/Components/oM/CreateCustom.cs
Closes #87 
The `CreateCustom` component now includes `IImmutable` classes in the types list.
The creation of these objects fails, and when it doesn't it returns an inconsistent object. 
They must be created via `Create` methods and `CreateCustom` should not include them in the list of possible types.
This pr is excluding them from the that list.
You can check that there are no `IImmutable` in the list when using a `CreateCustom`, right-clicking on it and looking for `BoundaryRepresentation` for example.
The test file is to ensure the rest works as before.
https://burohappold.sharepoint.com/:f:/s/BHoM/EmZKk1_KH09NuGEcr3KSvxIBgcw8reIJi3DuDZ3HBdlTSQ?e=4i7ZIQ
> Remove IImmutable from the list of types in the CreateCustom component

- UI_PostBuild/Program.cs
Closes #89 
When compiling a UI, the BHoM/Assemblies folder gets cleared. This means that if you build two UIs, you will get only the second one, since the first one gets wiped out.
I am adding a check for specific files, but this is not scalable. 
For the moment it is sufficient though, as we won't add a new UI every day.
No test file. To test, compile the Grasshopper_Toolkit first and then compile the Excel_Toolkit.
If the BHoM/Assemblies folder still contains the `.gha` file required by Grasshopper, the issue is considered fixed.
> Different UIs concur to fill the BHoM/Assembly folder

- BHoM_UI/Components/Engine/Explode.cs
Closes #72
When the same output in the explode component has objects of different types, it now crashes.
This pr sets the type to the generic `object`. It would be nice to have a way of getting the closest common type in the class hierarchy but I think it is not trivial. 
For the moment this provides a fix.
https://burohappold.sharepoint.com/:u:/s/BHoM/EfyyXnNHHAtNr-DRBKpqhekBmFR_uLV6JORfbNGIByJN8A?e=94bsyK
From @IsakNaslundBh 's example in the issue page
> BHoM_UI: Issue72-ExplodeMultipleTypesOnSameParameter

- UI_Engine/Compute/Organise.cs
Closes #92 
Removing the additional menu level that is now represented by `oM` and `Engine`.
The level collapsed and the entry `Engine` now is at the next menu level with the name `NonBHoMObjects`.
To test, compile the BHoM_UI and the Grasshopper_Toolkit. Add a `CreateObject` component and right click to see the changes to the menu.
> BHoM_UI: Issue 92 - MenuRenameNonBHoMObjects

- BHoM_UI/Components/Adapter/CreateQuery.cs
- BHoM_UI/Global/SearchMenu.cs
Closes #81 
Two actions on this pr:
1. The global menu now shows methods that return an `IQuery` object just once. On the master branch, the method will appear twice: once with the `CreateQuery` icon, and once with the `CreateObject` icon.
2. The `CreateQuery` component now only exposes the methods from the `Create` class, as its nae would suggest. At the moment, any method that returns an `IQuery` (e.g. a `Modify`) will appear in the local menu.
@ZiolkowskiJakub I think the biggest effect of this pr is on the Revit_Toolkit, and also it creates a user case to see of the menu works.
Since we are using the `ReturnType` of the method to build the menu tree, all the Revit_Toolkit queries are now in the `DataManipulation` branch, and not in the Revit branch anymore. I don't find this very …
> BHoM_UI - Issue 81 - deprecated query not hidden

- README.md
- UI_PostBuild/Program.cs
Closes #130 
This change should mirror same expected behaviour from compiling individual BHoM_Data repo directly. Namely:
On compilation of BHoM_UI and execution of `UI_PostBuild.exe` 
- all DataSets folders and containing .json files should be copied across to `...Roaming\BHoM\DataSets` preserving folder structure.
- from all `*_Toolkit` or `*_Datasets` repos 
- existing files should be overridden if modified
- additional folders or files in `...Roaming\BHoM\DataSets` created by user should be preserved. i.e. we are not doing a clean of the `...Roaming\BHoM\DataSets` folder.
With successful close out of this PR additional clean up and compliance issues around the Datasets can be raised and closed
> Update BHoM_UI postbuild.exe to copy Datasets .json files across from all repos

- BHoM_UI/Templates/MethodCaller.cs
- UI_Engine/Query/Weight.cs
Closes #143 
You can use the procedure described in #143 to test the issue inside and outside this pr.
- Fix crash happening when methods lie in the `global` namespace.
- Methods in the global namespace have now assigned the `Global` category.
> SearchMenu crashes the hosting UI if a method is defined in the `global` namespace

- BHoM_UI/BHoM_UI.csproj
- BHoM_UI/Components/oM/CreateObject.cs
- BHoM_UI/Global/SearchMenu.cs
- BHoM_UI/Templates/Caller.cs
- BHoM_UI/Templates/IItemSelector.cs
- BHoM_UI/Templates/IItemSelectorMenu.cs
- BHoM_UI/Templates/InputSelectorMenu.cs
- BHoM_UI/Templates/ItemSelector.cs
- BHoM_UI/Templates/ItemSelectorMenu.cs
- BHoM_UI/Templates/ItemSelectorMenu_WinForm.cs
- BHoM_UI/Templates/ItemSelectorMenu_Wpf.cs
- UI_Engine/Compute/Organise.cs
- UI_Engine/Create/Constructor.cs
- UI_Engine/Create/ConstructorText.cs
- UI_Engine/Query/SearchItems.cs
- UI_Engine/UI_Engine.csproj
Closes #151
Just play with the CreateOBject component and the global menu
- New Input selection menu for the CreateObject component
- Listing properties in text representation of generated constructors
- Improved behaviour of the WPF menus (used in Dynamo)
- Default value for all inputs of CreateObject component
See https://github.com/BHoM/BHoM_UI/pull/147 for a full discussion regarding those new features
> Refine the CreateObject component

- BHoM_UI/Components/oM/CreateObject.cs
Closes #163 
After an attempt of solving this problem within the Versioning_Toolkit, I ended up taking care of it directly in the BHoM_UI. The main reason for it is the lack of return type stored in the json version of a MethodInfo.  I tried to work with method Name and namespace to identify the return type but there was a few too many exceptions for my liking. Solving it here felt more robust and is after all a UI specific versioning issue. This doesn't change the fact that I will add a support for explicitly deprecated method in the versioning engine as planned. 
- Create some CreateObject components (make sure they use a specific Engine.Create method) and save the file. 
- Comment out the corresponding Create methods in the Engine and recompile
- Reopened the saved script file and make …
> Backward compatibility for removed Engine.Create methods

- BHoM_UI/Components/oM/CreateCustom.cs
Closes #159
Just make sure that the CreateCustom component is not allowing you to select a type from its menu and that it is still working for creating custom objects
Make sure to also check [the PR in Excel_Toolkit](https://github.com/BHoM/Excel_Toolkit/pull/170) as some changes were needed there to keep it compiling
> Remove the ability to create typed objects from the CreateCustom component

- UI_Engine/Convert/ToBHoM.cs
https://github.com/BHoM/BHoM_Engine/pull/1388
Fixes #172 
Load any create component into a UI using the default create component rather than a coder-created one from an engine
@adecler it was found during the investigation of this issue that you added `.PropertyType` to the `property` variable in the file which is changed, so I'm not 100% that this is the right fix. It fixes the problem I am trying to solve, but am cautious that it might thus mess something else up. As such, I would like to wait for a review from you before merging to double check just in case :smile: I'm asking for a review from the other UI developers to just make sure they're happy with Excel/GH/Dynamo points of view but final approval should come from @adecler
> Provide object descriptions if they're available on default create components

- BHoM_UI/Global/GlobalSearch.cs
- BHoM_UI/Global/SearchMenu.cs
- BHoM_UI/Global/SearchMenu_WinForm.cs
- BHoM_UI/Global/SearchMenu_Wpf.cs
Closes #104
See issues for testing procedure
This fixes the crash for Grasshopper. I have mirrored that for WPF although I have no way of testing it. I also have a feeling that there are other side effects to this unloading/reloading of GH but to be honest this feels like such a niche user case that I will investigate only on a need-to-fix basis.
> Clear global menu when GH is unloaded

- BHoM_UI/BHoM_UI.csproj
- BHoM_UI/Components/Engine/Explode.cs
- BHoM_UI/Components/oM/CreateObject.cs
- BHoM_UI/Global/GlobalSearch.cs
- BHoM_UI/Global/SearchMenu.cs
- BHoM_UI/Global/SearchMenu_WinForm.cs
- BHoM_UI/Global/SearchMenu_Wpf.cs
- BHoM_UI/Templates/ParamSelectorMenu.cs
- UI_Engine/Query/Hits.cs
- UI_Engine/Query/Weight.cs
- UI_oM/SearchItem.cs
https://github.com/BHoM/BHoM_Engine/pull/1437
This is not a strict dependency in term of code compilation but the change in the UI have highlighted a bug in the engine so better to test with that PR.
Closes #183 
Closes #196 
- Allow to remove outputs for the Explode component
- Show BHoM menu on wire drag-and-released event
- Note that if you are doing a test in Excel, you will need this PR for the global menu to still work properly: https://github.com/BHoM/Excel_Toolkit/pull/190
- I am fixing two issues in this PR because those were the issues that had code change overlapping with the adapter level 4 PRs. So it was easier for me to store them and submit them as a batch.
> Allow to remove outputs for the Explode component and show BHoM menu on wire drag-and-released event

- BHoM_UI/Components/Engine/Explode.cs
Closes #197
To explain my fix a little more: 
- The code was actually explicitly outputting a `typeof(object)` when the same property name with the same property type was appearing twice
- It was also injecting a bug where, if we had multiple properties with the same name but different types, only the type of the last property would be kept
- The idea with the system is that ALL types under the same name are collected so we can find a common type later (for the moment, always `typeof(object)`. So the solution is ultra simple: just add the type to the list.
See test file provided in issue
I have added the case where properties with the same name have different type to make sure:
> Fix Explode output type

- BHoM_UI/Templates/Caller.cs
Closes #210 
After more digging, the issue did not seem to have anything to do with GH crashes on startup, but had to do with versioning toolkit not being triggered at all for the old way of serialising components. Hence, solution below.
Adding a call to Versioning_Engine, `ToNewVersion` for old component if the first deserialisation of the method returns null.
Code looks safe on the Versioning_Engine side, but needs to be tested through properly to make sure it does not break other things, and can only be tested on scripts saved before new serialisation. This is before early July 2019.
Example test files found here: https://burohappold.sharepoint.com/:f:/s/BHoM/ErCbq8ntwdJKi1dnjOUv2ZwBLyBl9mRYRvSv3vSORMbsug?e=YvMu8q
As this is touching very core framework methods, would be good to get …
> Adding ToNewVersion call for old component deserialisation

- BHoM_UI/Components/Engine/SetProperty.cs
Closes #226 
Deep clone input to have its property set to make sure the input does not get changed.
This was causing issues when multiple layer property set was being used, causing the upstream obejcts to be changed.
https://burohappold.sharepoint.com/:f:/s/BHoM/Es1XVgVIo6xAqXPRZyndtbkBv89NqlXKMUkRutdRaWHNSw?e=zpHf64
> Ensuring immutability for SetProperty by deep cloning object

- UI_Engine/Query/Items.cs
Closes #230 
Simply make sure that auto constructors are not available in the UI for types that already contain a constructor (e.g. `IImmutable` and `FragmentSet`). All types without defined constructor should still have one generated.
- There was no way to detect that a constructor was generated by the compiler. I though I could get that from the `CompilerGeneratedAttribute` attribute but that doesn't work since that attribute is not found even on compiler generated constructors.  So I considered that all constructor without arguments is compiler generated. 
- I removed the check on `Immutable` since the check on the number of non-empty constructor covers them.
> Avoid generating constructor for types with defined constructor

- BHoM_UI/Templates/Caller.cs
Closes #214
@kThorsager , I'll let you use whatever file works for you (the one provided in the issue was not reproducing the bug for me so I created my own fake scenario).
> Fix wire disconnects for edge cases of Versioning

- UI_PostBuild/CleanDirectory.cs
- UI_PostBuild/CopyAssemblies.cs
- UI_PostBuild/CopyDatasets.cs
- UI_PostBuild/CopyUpgrades.cs
- UI_PostBuild/Program.cs
- UI_PostBuild/UI_PostBuild.csproj
- UI_PostBuild/packages.config
https://github.com/BHoM/BHoM/pull/823
https://github.com/BHoM/BHoM_Engine/pull/1693
https://github.com/BHoM/Versioning_Toolkit/pull/70
Closes #245 
Closes #243 
Versioning is now decentralised to each project where changes happened. 
- For method versioning, use the `PreviousVersion` attribute on the new method.
- For everything else, use the `Versioning_32.json` at the root of the project folder.
- Also closes #243 as it was a very simple and obvious task on the UI_PostBuild
- The content of an empty `Versioning_32.json` file is as follow:
```json
{
"Namespace": {
"ToNew": {
},
"ToOld": {
}
},
"Type": {
"ToNew": {
},
"ToOld": {
}
},
"Properties": {
"ToNew": {
},
"ToOld": {
}
}
}
```
> Post build: Decentralise versioning

- BHoM_UI/Components/oM/CreateObject.cs
- BHoM_UI/Templates/Caller.cs
https://github.com/BHoM/BHoM/pull/853
https://github.com/BHoM/BHoM_Adapter/pull/228
https://github.com/BHoM/BHoM_Engine/pull/1743
(at least for testing)
Closes #154
`IEnumerable` types are can now be properly inputted as lists:
Use any CreateObject component as add inputs for Tags and Fragments.
I had to do a second commit to fix a problem created from a previous PR: Added inputs to a `CreateObject` component would not work properly after copy paste or reopening the file.
> Handle HashSet, FragmentSet,... as input list

- UI_PostBuild/CopyUpgrades.cs
Closes #251
I decided to go with Al'second option. I mentioned that it would not work for the Dynamo folder but I started to think this is actually a good thing. That folder is purposefully structured to avoid being transferred to the Roaming folder so it makes sense that it also avoid the versioning picking. Something to deal with Dynamo toolkit either way and should not influence what is done here.
> UI_PostBuild: Fix UnauthorizedAccessException on PostBuild CopyUpgrades

- BHoM_UI/Global/GlobalSearch.cs
Help fixing https://github.com/BHoM/Grasshopper_Toolkit/pull/513
See that PR for details
> Provide a way to remove event handles from outside the GlobalSearch class

- BHoM_UI/Templates/MethodCaller.cs
Closes #265
https://burohappold.sharepoint.com/:u:/s/BHoM/Ea5xdAvCGIFNjNsL0a7vIp0BVnVz5v5_H1XqPuOV2hIFwA?e=vDwxva
You will need https://github.com/BHoM/BHoM_Engine/pull/1740 and https://github.com/BHoM/BHoM/pull/852 to test with that file
The `ItemsInRange` component already saved will still fail but any new component created and copy/saved will work fine.
> Overwrite MethodCaller.Write() so it saves its original method

- BHoM_UI/BHoM_UI.csproj
- BHoM_UI/Templates/Caller.cs
- BHoM_UI/packages.config
https://github.com/BHoM/BHoM_Engine/pull/1762  
(at least on a behavioural level so recommend to review them together)
Closes #262
Without this, you will have missing wires when testing https://github.com/BHoM/BHoM_Engine/pull/1762  
Old files that contain components that need upgrading
> Align with auto-versioning during serialisation

- BHoM_UI/Global/SearchMenu.cs
Closes #252
See issue for full discussion. Thre things are done in this PR:
- Refresh the display text for those to match Al's suggestion
- Move them to a separate method to better highlight their existence and improve availability separately from the other search items if needed
- Fix the name of `Delete` -> `Remove` and `CreateDictionary` that was named `CreateCustom`
I recommend, reviewing this alongside https://github.com/BHoM/Grasshopper_Toolkit/pull/515 as the two PRs are closely related.
> Update SearchItems for components

- BHoM_UI/Templates/Caller.cs
> BHoM_UI: Add support for "&" ByRef types in Caller

- BHoM_UI/Templates/Caller.cs
Closes #272 
Adding a get full name method that concatenates `BH` and the `Category` and `Name` of the caller, to help standardise the 'full name' across other UI's rather than construct their own.
> Add GetFullName() method to caller

- BHoM_UI/BHoM_UI.csproj
- UI_Engine/UI_Engine.csproj
- UI_PostBuild/CopyUpgrades.cs
- UI_PostBuild/Program.cs
- UI_PostBuild/UI_PostBuild.csproj
- UI_oM/UI_oM.csproj
https://github.com/BHoM/admin/issues/5
- Add two new arguments to UI_PostBuild: 
- `--onlyUpgrades`: use this to make sure only upgrade files are created (no dll or dataset)
- `--cleanTargetDir`: use this to have the target folder cleared first
- Keep the content of the existing `Upgrades.json` file by adding to it instead of replacing it
- Change BHoM_UI postBuild target folder
- @IsakNaslundBh , I kept the target folder to `Assemblies/bin` to mirror what you did in the engine (`ToNewVersion` file) but actually very easy to use the `BHoM/Upgrades` folder instead as nothing changes in the code, only in the post build command 
- To test the Post_Build process properly, please use https://github.com/BHoM/Versioning_Toolkit/pull/77
> Update postbuild and references to ProgramData

- BHoM_UI/Components/oM/CreateObject.cs
- BHoM_UI/Templates/Caller.cs
Closes #278
PR #263 broke the ability for the `CreateObject` component to add and remove inputs. The reason is that we lost the ability to easily know if the `SelectedItem` was upgraded by the Versioning engine since it is now black-boxed inside the `FromJson` method. So, in that PR, I tried to detect an upgrade by comparing the inputs and outputs. The problem is that I forgot the case of `CreateObject` where inputs can be modified by the user.
I have now overridden in `CrerateObject` the check done in `Caller`. If the `SelectedItem` is a type, I just make sure that all the component inputs can still be found as property of the object. 
This component is getting messy and too fragile for my liking so I will review it properly next quarter with the general review of the UI. But this PR …
> Fix detection of upgraded SelectedItem for Types

- BHoM_UI/Components/oM/CreateObject.cs
Closes #284
as stated in issue:
When `SetItem` is called for the general case that a method is being picked, `m_OriginalMethod` is being handled and set to the corresponding method or nulled out if not used in the `SetItem` on the method called.
On the CreateCaller on the other hand, when a type is selected, `m_OriginalMethod` is not touched.
For Grasshopper and dynamo this is not an issue, as they have a one-to-one relation between a component and one caller. For excel on the other hand this becomes an issue, as Excel_UI only owns one of each caller type, which is being used for all the calls that goes through that particular caller.
This means that if a create method is called, followed by a property assignment method, basically method followed by type, `m_OriginalMethod` is still set …
> Set m_OriginalMethod to null when selecting a type

- UI_Engine/Compute/LogUsage.cs
- UI_Engine/UI_Engine.csproj
- UI_oM/UI_oM.csproj
- UI_oM/UsageLogEntry.cs
Closes #289 
This saves the component usage in log files. The files are located in `C:\ProgramData\BHoM\Logs`. 
- To avoid the potential issue of multiple UIs writing to the same file, I simply have each UI writing into its own. The fil name convention is `Usage_<uiName>_<CreationTimeInTicks>.log`. I think that reduces teh risk of having files with the same name down to zero :smile:.
- Each record saves the following:
- Time of recording
- UI hosting the component
- Component Id
- Selected BHoM item for the component
- Error events (that should help us identify which component needs fixing even if the user doesn't raise an issue)
- Note that I considered recording the name of the file containing the component but decided against it because this gives away information that people might not …
> Adding ability to log component usage

- BHoM_UI/BHoM_UI.csproj
- BHoM_UI/Global/Initialisation.cs
- BHoM_UI/Templates/Caller.cs
- UI_Engine/Compute/LogUsage.cs
- UI_Engine/Compute/SaveSettings.cs
- UI_Engine/Query/Settings.cs
- UI_Engine/UI_Engine.csproj
- UI_oM/Interfaces/IInitialisationSettings.cs
- UI_oM/Interfaces/ISettings.cs
- UI_oM/UI_oM.csproj
- UI_oM/UsageLogEntry.cs
Supports the [PR in BHoMAnalytics](https://github.com/BHoM/BHoMAnalytics_Toolkit/pull/2).
This now provides a solution for toolkits to save some settings in `C:\ProgramData\BHoM\Settings`. Basically, each toolkit can have its own config file with the corresponding name there. I have exposed the methods to read and save settings so users can modify those settings without having to mess directly with a json file. Two immediate usages of this come to mind:
- BHoMAnalytics can store the information about the database where the usage data is sent -> that's what the BHoMAnalytics PR does)
- User settings for the UI (e.g. user tags, customised look,....) -> soon in oyu favorite BHoM UI 😄 
The other thing I did here is to let the toolkits execute some code when the BHoM is started. This is …
> Create toolkit setting system

- BHoM_UI/Caller/Read.cs
Closes #303
See issue
The name input is still incorrect as expected due the component being saved in an incorrect state. Even if I don't plan to cover all cases of components saved in incorrect state, there is things we can do to improve the handling of this specific situation. That needs to be done in Grasshopper though as BHoM_UI itself has no way of knowing the state of the GH components.
> Fix bug when deserialising components saved with input duplicates

- BHoM_UI/Global/Initialisation.cs
Not sure if it actually solves the problems but this is related to issues #305. 
I suggest we keep that issue open even if we merge this PR though. As I never had that issue on my machine, this PR is just a blind guess at what might be causing the issue. An additional try-catch cannot hurt though 😄 
It is worth mentioning that 
- BHoM_Analytics is running asynchronously so there is not risk there for it to freeze Grasshopper. 
- Usage log files are not accessed during initialisation so no risk on that side either.
Keep opening and closing Grasshopper I guess 😋
> Possible fix to Grasshopper sometimes freezing at launch

- BHoM_UI/Components/Engine/SetProperty.cs
Closes #309
When running the testing procedure on Grasshopper today, I realised the input type of the `SetProperty` was correctly staying on `List` after reopening the file. This was in contradiction with issue #309.
The problem was that, since the time when that file was created, Grasshopper is now asking BHoM_UI to update internal types of parameters when they are modified by the user. So here's the situation:
- On test file: the `value` input was saved as an `Object`
- On any new `SetProperty` component: the `value` input was saved as an `List<Object>`
Intuitively, the new version feels better but, here's the catch: when the `SetProperty` component is deserialised, it doesn't know what object it has to set the property of yet so it will always consider the type of `value` as `Object`. …
> Prevent input types to be modified by user for SetProperty

- BHoM_UI/Caller/IO_CRUD.cs
- BHoM_UI/Components/Engine/Explode.cs
Closes #318
Dynamo doesn't always provide valid parameters (name and type) to `Caller.UpdateInput` so safer to add a few extra checks.
I have also allowed name to be null for additional flexibility on when that method can be triggered.
As soon as this PR is merged, I'll push the changes on the side of Dynamo to the open PR.
A  simple review of the code should be enough here as it is purely adding null checks
> Adding null checks to Caller.UpdateInput

- BHoM_UI/Menus/ParamSelectorMenu.cs
Closes #320
See issue
Just check the menu after deleting some of the inputs using the `-` button both in Grasshopper and Dynamo.
> Fix ParamSelector menu getting out of sync in Dynamo

- BHoM_UI/Caller/Read.cs
- BHoM_UI/Caller/Run.cs
- UI_Engine/Create/ParamInfo.cs
- UI_Engine/Query/Items.cs
- UI_oM/ParamInfo.cs
https://github.com/BHoM/BHoM/pull/1020
https://github.com/BHoM/BHoM_Engine/pull/2057
Closes #205
see the oM PR for more details
The support for converting deleted Create methods into auto-constructors was already existing in the BHoM_UI code but was broken after the refactoring. It was a small enough fix and relevant enough for this PR that  Ideceided to do it here.
Closes https://github.com/BHoM/Versioning_Toolkit/issues/96
Just add those attributes to your favorite class and test that it works in the UI
> Leverage attributes to better control auto-create components

- BHoM_UI/Components/Engine/SetProperty.cs
https://github.com/BHoM/BHoM_Engine/pull/2066
See https://github.com/BHoM/BHoM_Engine/pull/2066 for details
Just make sure that the `SetProperty` component is still working for both new and saved ones. Note that I have also tested for setting of subproperies and it still works fine (e.g. `Location.X`). The other cool thing is that the `SetProperty` component is not limited to BHoM objects anymore (before, you couldn't set a property of a BHoM Point for example). That aligns better with previous changes on things like `ToJson`
> Align to change in SetProperty method name

- BHoM_UI/Caller/SetInputs.cs
- UI_Engine/Query/MatchWith.cs
- UI_oM/PreviousNamesFragment.cs
- UI_oM/UI_oM.csproj
https://github.com/BHoM/BHoM/pull/1062
Closes https://github.com/BHoM/Grasshopper_Toolkit/issues/561
(might have to close manually that one)
When multiple method arguments of the same type have their name changed, the wires are lost after reopening the file. This fixes that by providing a new `PreviousInputNamesAttribute`. 
- Create a component that has multiple inputs of the same type, connect all the inputs and save the file.
- Change those inputs names on the method itself and recompile
- Check that the wires have disappeared if you reopen the file.
- Add the new `PreviousInputNamesAttribute` for those changed inputs and recompile
- Check that the wires are still there when you reopen the file.
> Improved name change support on method arguments

- BHoM_UI/Components/Engine/SetProperty.cs
https://github.com/BHoM/BHoM_Engine/pull/2142
Closes #141 
With this PR, it is now easy to clear the value of a property by leaving the `value` input empty. Here's how it behaves:
- Value types like primitives and enums are set to their default value (value types cannot be null)
- Any IEnumerable is set to an empty version of that type.
- Strings are set to an empty string (it could be set to null but I think this is the only case where it makes more sense not to)
- All other objects are set to null.
Looks like a lot of cases listed like that but I found it pretty intuitive when actually used. Let me know if you disagree.
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_UI/BHoM_UI-Issue141-SetPropertyDefault.gh?csf=1&web=1&e=h7RH22
Note that …
> Make it easy to clear the value of a property

- BHoM_UI/Components/Engine/GetEvents.cs
- BHoM_UI/Global/Initialisation.cs
- BHoM_UI/Global/SearchMenu.cs
https://github.com/BHoM/BHoM/pull/1092
Closes #335
It seems that some events recorded in Revit are using UTC time instead of local time despite using `DateTime.Now` and not `DateTime.UtcNow`. So detecting startup events can only be done reliably using UTC time everywhere. 
It is important to note, that I keep using local time for the `since` input of `GetEvents` because this is something provided by the user.
> BHoM_UI: Detect startup using UTC time instead of local time

- .ci/code/UI_Test/Helpers/InstantiateCaller.cs
- .ci/code/UI_Test/Helpers/PossibleComponentItems.cs
- .ci/code/UI_Test/Objects/DummyAccessor.cs
- .ci/code/UI_Test/Objects/DummyCaller.cs
- .ci/code/UI_Test/Verify/ComponentInstantiation.cs
- .ci/code/UI_Test/Verify/ComponentReadWriteCycle.cs
- .ci/code/UI_Test/Verify/ComponentRunCycle.cs
- UI_Engine/Query/Items.cs
Closes #363
As per title. also mirror the changes that were made on the script testing BHoM_UI
You can simply call `.\TestRunner.exe UI` but I find there is still a few too many errors for this to be easily readable at the moment.
So I used this as well: https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_UI/CICD-%23363-AlignToTestToolkitChanges/TestRunner_UI.gh?csf=1&web=1&e=yRqvAl
This basically is a bunch of C# components that  call directly the tests inside UI_Test.dll. Since those return a `TestResult` it is easy to do a few explodes to get exactly the data you want out of it.
Right now, here's the errors that I have. 
```
BH.oM.Adapters.Sharepoint.Requests.AndCondition.AndCondition() {String Name, List<ICondition> Conditions} …
```
> CI/CD: Align to changes in Test_oM and Test_Engine

- UI_Engine/Create/InputAccessor.cs
- UI_Engine/Create/ParamInfo.cs
Closes #368
See issue for more details.
`./TestRunnre.exe UI`
- Note that methods with a out input are now working BUT the out parameter is still an input, not an output. There is a separate issue for that here: https://github.com/BHoM/BHoM_UI/issues/313
- I recommend testing with the PR on SharePoint that fixes some invalid object to reduce the amount of noise you getting in the results of TestRunner
- Personally, I now get this resut from the testRunner:
```
PS C:\ProgramData\BHoM\Assemblies> .\TestRunner.exe UI
Testing input and output handling of the 7157 available BHoM components.
0 errors and 0 warnings reported.
Testing copy of the 7157 available BHoM components.
4 errors and 0 warnings reported.
Inner results:
BH.Engine.Adapter.Query.AdapterId(IBHoMObject bHoMObject, Type …
```
> Fix failing components for methods with ref, out, or structure parameters

- UI_Engine/Compute/SaveSettings.cs
- UI_Engine/Query/Settings.cs
Closes #312
`\` are now replace with `/` to keep the API happy. 
Note that I couldn't find any `\` in `BH.oM.UI.ISettings` but have fixed the other two files listed in the issue.
> Remove backslash from Descriptions

- BHoM_UI/Caller/IO_CRUD.cs
- BHoM_UI/Components/Engine/SetProperty.cs
- BHoM_UI/Components/oM/CreateCustom.cs
Closes #351 
Up until now BHoM_UI was trusting individual UIs (GH, Excel,...) to only request an input update when it was necessary but it seems that Grasshopper was a bit to eager to request upgrades even when just a wire was connected to that input (i.e. no input menu interaction from the user). Since only the `CreateCustom` component actually allows update from the user, I set up the default to ignore any request from the UIs. (`SetProperty` and Explode where already doing their own thing without the need for user input).
In the case of the test file provided, Grasshopper was handling the positions as objects and not decimals and requesting BHoM_UI to change to that type. I have created a [separate issue](https://github.com/BHoM/Grasshopper_Toolkit/issues/605) to look into what …
> Better control when input parameters can be upgraded by the user

- UI_Engine/Compute/SetProjectID.cs
Closes #378 
A warning message has now been provided to the user for the case of providing an empty string as input into the `SetProjectID` component.
Expected behaviour in Grasshopper is now
Test using the `SetProjectID` with inputs of either an empty string or a valid ID to check correct messages occur. See expected new behaviour above.
> Provide user feedback for empty string on Set Project ID

- UI_Engine/Compute/LogUsage.cs
Closes #382
Two arguments were added to the LogUsage method in [this PR](https://github.com/BHoM/BHoM_UI/pull/370). Since this is a public Engine method, it should have provided versioning.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_UI/%23282-LogUsageVersioning?csf=1&web=1&e=SixCyu
`LogUsage` should not appear in the list of failing methods
Alternatively, you can just pass this to a `FromJson` component and make sure it deserialise correctly:
```
{ "_t" : "System.Reflection.MethodBase", "TypeName" : "{ \"_t\" : \"System.Type\", \"Name\" : \"BH.Engine.UI.Compute, UI_Engine, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null\" }", "MethodName" : "LogUsage", "Parameters" : ["{ \"_t\" : \"System.Type\", \"Name\" : \"System.String, …
```
> UI_Engine: Add versioning for LogUsage

- BHoM_UI/BHoM_UI.csproj
Set the .NET framework version of the projects in this toolkit to 4.5.2
This PR will be reviewed by making sure that an installer can be produced from it.
> Set .NET framework version to 4.5.2

- BHoM_UI/Components/oM/CreateData.cs
Closes #400 
Checking if the dataset contains a SourceLink, and if so, add a link to it in the menu. Really useful to have quick direct access to the source of the data, when available.
Added the functionality for both the Toolstrip and WPF, but was not able to test the WPF as I do not know where it is being called from. Tried in dynamo, but looked as if the menu is only triggered once, when you add the component, and not again when a dataset has been selected. Happy to remove the WPF implementation if we think that is a better way to go.
Any of the UK steelsection or EU material datasets should have working links:
> Adding link to source for CreateDataCaller

- BHoM_UI/Caller/Read.cs
Done in support of https://github.com/BHoM/BHoM_Engine/pull/2738/files but does not require that to compile.
Adding support for single type matching of inputs to be replaced when going from Create method to PropertyAssignment create method. This is what is done on the updates side, so should be a simple alignment with what is done there.
> Add support for single matching input for Create method replacement of Type

- BHoM_UI/Components/Engine/Explode.cs
Closes #423 
See #423 for the test script.
Before this PR, the script will return an error on the Explode component, returning no output (not even for the retrievable properties).
After this PR, the script should behave as this:
> Improve `Explode` component behaviour when object has some non-retrievable properties

- UI_Engine/Compute/LogUsage.cs
- UI_Engine/UI_Engine.csproj
- UI_oM/TriggerLogUsageArgs.cs
- UI_oM/UI_oM.csproj
See the details listed on [this linked PR](https://github.com/BHoM/BHoMAnalytics_Toolkit/pull/35).
> Add ability to connect and trigger events when Usage Log is triggered

- UI_Engine/Compute/LogUsage.cs
- UI_Engine/Query/UsageLogFileName.cs
- UI_Engine/Query/UsageLogFolder.cs
- UI_Engine/UI_Engine.csproj
> Add ability to query the usage log file name for external toolkits to the UI

- UI_Engine/Compute/LogUsage.cs
> Add event to be triggered when the UI is closing

- BHoM_UI/Global/DocumentListener.cs
- UI_Engine/Compute/LogUsage.cs
- UI_Engine/Objects/DocumentLoading.cs
- UI_Engine/UI_Engine.csproj
> Trigger for UI Loading events during analytics logging

- UI_Engine/Compute/LogUsage.cs
- UI_Engine/Objects/DocumentLoading.cs
Allows events to hook onto when the UI has finished opening.
> Add event for when the UI is finished opening

- BHoM_UI/Components/Engine/GetInfo.cs
- UI_Engine/Query/Information.cs
- UI_Engine/UI_Engine.csproj
- UI_oM/BHoMInformation.cs
- UI_oM/UI_oM.csproj
Fixes https://github.com/BHoM/BHoM_Engine/issues/2971
Also adds the install date to `GetInfo`
> Add Information component for UI elements and update GetInfo to include full install version information

- BHoM_UI/Components/oM/CreateEnum.cs
Closes #447
Create `DensityExtractionType` enum in Grasshopper and see if the first option shows as `AllMatching` (current) or `All matching.` (desired).
> Enum.GetNames replaced with IToText on enum label generation to leverage DisplayText attribute

- BHoM_UI/Caller/SetInputs.cs
- UI_oM/ParamInfo.cs
Fixes #455 
This provides the UIExposure information to the `ParamInfo` object used by all UIs downstream.
Each UI will be responsible for handling how they opt to display or not display something with `IsExposed = false` depending on each UIs requirements.
> Utilise Exposure in ParamInfo

- UI_Engine/Query/OutputParams.cs
Closes #478 
[ExplodeDeleteTest.zip](https://github.com/BHoM/BHoM_UI/files/13833322/ExplodeDeleteTest.zip)
The call to `OutputParams` was very slow (~20s) so I added it to the scrip to confirm in now takes only a few milliseconds.
> Solving the slow execution of CollectOutputTypes on Custom objects

- BHoM_Windows_UI/Settings/SearchSettingsWindow.xaml
- BHoM_Windows_UI/Settings/SearchSettingsWindow.xaml.cs
https://github.com/BHoM/BHoM_Engine/pull/3300
https://github.com/BHoM/BHoM_Engine/pull/3302
https://github.com/BHoM/BHoM_Engine/pull/3304
Fixes #483 
Same as #482 
Use this JSON file to load in and see what changes you get: 
[BH.oM.UI.SearchSettings.json](https://github.com/BHoM/BHoM_UI/files/14418386/BH.oM.UI.SearchSettings.json)
Try to break the JSON file and check you get errors as well.
You should find the first few alphabetical options are unchecked, and you should get a new addition of `ABCDEF` being checked - it will likely render at the bottom first but on a reload of the settings window you'll find it at the top.
I have removed the `Reset` button because this was effectively duplicating the `Select/Unselect all` buttons, and it was only resetting to check everything rather than …
> Add ability to load settings

- BHoM_UI/Caller/Run.cs
https://github.com/BHoM/BHoM_Engine/pull/3307
Fixes #485 
You may be wondering why I've opted to query the suppression state to then reset it, however, the use case for this is if a user of visual programming has, for whatever reason, opted to suppress things themselves, we don't want to blindly reset the suppression after a method runs in case it failed to reset it itself.
The UX on that would be this:
- User sets error suppression to true
- User runs component which also sets warning suppression to true
- Component crashes out and does not reach the reset option
- UI resets suppression, error suppression is now false along with warning suppression
- User is confused as to why their error suppression isn't working
This could also be the case for methods which don't crash:
- User sets …
> Update run to reset log suppression after running component

- UI_Engine/Compute/Constructor.cs
- UI_Engine/Compute/ConstructorText.cs
- UI_Engine/Compute/SaveSettings.cs
- UI_Engine/Create/ParamInfo.cs
- UI_Engine/Query/AreMatching.cs
- UI_Engine/Query/Settings.cs
Closes #488 
Fixed documentation compliance, and some fixes to code compliance (namely extension method fixes, though ignoring input/output accessor fails).
> Fixed documentation compliance

- .ci/BHoMBot/Nuget/BHoM.UI.nuspec
Closes #493 
Fairly straightforward. I simply removed the extra `.0` in the target framework. So this should be pretty quick and easy to review.
> Fix target framework in the nuspec file

- BHoM_UI/Global/DocumentListener.cs
Closes #508 
Fixes an issue with the versioning log window. Previously was handled on a separate thread that was aborted on document close. Thread.Abort() is not supported in later runtimes, see [This link](https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.abort?view=net-9.0#system-threading-thread-abort).
This has now been refactored out by instead storing the versioning form in a static varibale, and closing and disposing it at document close and open.
Also changing from ShowDialog to Show and bringing it to top.
For grasshopper, this can be tested with files in [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&web=1&e=0c6Dk1&CID=9709424f%2De63b%2D413d%2D9539%2Dbdbd6a77c5bc&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=% …
> Fix issue with versioning log and thread abort

- UI_Engine/Compute/LogUsage.cs
- UI_oM/TriggerLogUsageArgs.cs
Add support for retreiving projectId from events fired. If projectId is set upon return from TriggerUseageLog, then Id is used for the current file and set to update and stored for future useage.
> Add ProjectId to triggerUseageLogArgs and check if set and update ProjectId

- BHoM_UI/Caller/Compile.cs
- BHoM_UI/Caller/IO_CRUD.cs
- BHoM_UI/Caller/Run.cs
- BHoM_UI/Components/Engine/SetProperty.cs
- UI_Engine/Compute/InputAccessor.cs
- UI_Engine/Compute/OutputAccessor.cs
Fixes #512
See issue for details
Code compliance should now pass
> Fixing Code Compliance issue on Create.InputAccessor and Create.OutputAccessor

- BHoM_UI/Caller/Compile.cs
- BHoM_UI/Caller/Core.cs
- BHoM_UI/Caller/Run.cs
- BHoM_UI/Components/Engine/Modify.cs
- BHoM_UI/Components/oM/CreateObject.cs
- UI_Engine/Compute/OutputAccessor.cs
- UI_Engine/Create/OutputAccessor.cs
- UI_Engine/Query/OutputParams.cs
- UI_Engine/UI_Engine.csproj
https://github.com/BHoM/BHoM/pull/1677
Addresses the issue raised in the BHoM. See https://github.com/BHoM/BHoM/pull/1677 for more details.
> Add support for dynamic objects
