BHoM/BHoM_UI

BHoM_UI/BHoM_UI.csproj, BHoM_UI/Global/SearchMenu.cs, BHoM_UI/Global/SearchMenu_WinForm.cs, BHoM_UI/Global/SearchMenu_Wpf.cs, UI_oM/ComponentRequest.cs, UI_oM/UI_oM.csproj
Fixes #58.
@epignatelli , let me know if that does it for you. You will still probably have to translate that into coordinates inside the canvas but it should otherwise do the trick.
=> BHoM_UI - Issue 58 - provide the location of the new component to be created when using gobal menu

BHoM_UI/Components/Adapter/CreateAdapter.cs, BHoM_UI/Components/Adapter/CreateRequest.cs, BHoM_UI/Components/Engine/Compute.cs, BHoM_UI/Components/Engine/Convert.cs, BHoM_UI/Components/Engine/Modify.cs, BHoM_UI/Components/Engine/Query.cs, BHoM_UI/Components/oM/CreateData.cs, BHoM_UI/Components/oM/CreateEnum.cs, BHoM_UI/Components/oM/CreateObject.cs, BHoM_UI/Components/oM/CreateType.cs, BHoM_UI/Global/SearchMenu.cs, BHoM_UI/Properties/AssemblyInfo.cs, UI_Engine/Properties/AssemblyInfo.cs, UI_Engine/Query/SearchItems.cs, UI_Engine/UI_Engine.csproj, UI_PostBuild/Properties/AssemblyInfo.cs, UI_Test/Properties/AssemblyInfo.cs, UI_oM/Properties/AssemblyInfo.cs
Depends on: https://github.com/BHoM/BHoM_Engine/pull/1062
Closes #98 
This change follows the on e in the dependent pull request in the `Reflection_Engine`.
The `CreateTypes` component now includes these interface types.
https://burohappold.sharepoint.com/:f:/s/BHoM/Emt9HMps2LpCrd4zxetp_4MBOHYnPOmtva-yzsLO9BDuvA?e=pSFHiz
=> BHoM_UI - Issue 89 - Include interface types into the CreateTypes component

BHoM_UI/Components/Adapter/Execute.cs, BHoM_UI/Components/Adapter/Move.cs, BHoM_UI/Components/Adapter/Pull.cs, BHoM_UI/Components/Adapter/Push.cs
Closes #107 
Output names added and descriptions aligned
N/A
=> BHoM_UI: Added outputs and changed adapter descriptions to match. #107

.github/ISSUE_TEMPLATE/api_changed.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/compliance.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/ISSUE_TEMPLATE/test_script.md
Closes #113 
Adding issue templates to the repo.
=> BHoM_UI: Add issue templates

BHoM_UI/Components/Adapter/Delete.cs, BHoM_UI/Components/Adapter/Execute.cs, BHoM_UI/Components/Adapter/Move.cs, BHoM_UI/Components/Adapter/Pull.cs, BHoM_UI/Components/Adapter/Push.cs, BHoM_UI/Components/Adapter/UpdateProperty.cs
https://github.com/BHoM/BHoM_Adapter/pull/128
Refactor to follow https://github.com/BHoM/BHoM_Adapter/pull/128
https://burohappold.sharepoint.com/:f:/s/BHoM/EuLYM_Y59tNMkVjQSVhuo1cBXNxPclS8Ly7EmEzd3fRhHg?e=0UriL3
* Renamed the method called from the "Move" component from `PullTo` to `Move`
* Added `config` parameter in the Move component so that user can input both `pullConfig` and `pushConfig`
=> Modify Move component to reflect changes in BHoM_Adapter

BHoM_UI/BHoM_UI.csproj, BHoM_UI/Properties/AssemblyInfo.cs, UI_Engine/Properties/AssemblyInfo.cs, UI_Engine/UI_Engine.csproj, UI_PostBuild/Properties/AssemblyInfo.cs, UI_Test/Properties/AssemblyInfo.cs, UI_Test/UI_Test.csproj, UI_oM/Properties/AssemblyInfo.cs, UI_oM/UI_oM.csproj
Closes #134 
- Prevent the copy of redundant assemblies by setting Copy Local to false
- Update `AssemblyVersion` to `2.4.0.0` for the BHoM_UI
- Update `AssemblyVersion` to `2.4.0.0` for the UI_Engine
- Update `AssemblyVersion` to `2.4.0.0` for the UI_oM
- Update `AssemblyVersion` to `2.4.0.0` for the UI_PostBuild
- Update `AssemblyVersion` to `2.4.0.0` for the UI_Test
=> B ho m ui#134 copy local+assembly version

BHoM_UI/Properties/AssemblyInfo.cs, UI_Engine/Properties/AssemblyInfo.cs, UI_PostBuild/Properties/AssemblyInfo.cs, UI_Test/Properties/AssemblyInfo.cs, UI_oM/Properties/AssemblyInfo.cs
Closes #145
Make sure that:
- All the .csproj files in the solution have the properties  `AssemblyFileVersion` to `3.0.0.0` and `AssemblyVersion` to `3.0.0.0`.
- The AssemblyCopyright reads `[assembly: AssemblyCopyright("Copyright © https://github.com/BHoM")]`
- Update `AssemblyFileVersion` to `3.0.0.0`
- Update `AssemblyVersion` to `3.0.0.0`
=> Update AssemblyVersion and AssemblyFileVersion to 3.0.0.0

BHoM_UI/Components/Engine/GetProperty.cs
Closes #182
This is the computational time before fix:
And after the fix:
=> Fix slow GetProperty component

BHoM_UI/Templates/Caller.cs
Closes #179
Closes https://github.com/BHoM/BHoM_Engine/issues/1375
Since the code was already on my machine, I thought I might as well pull request it. Don't take this as  the final say on how to solve #179 though. I am happy to iterate on it as needed.
=> Improved error message when exception reached Caller.Run

BHoM_UI/BHoM_UI.csproj, BHoM_UI/Components/Adapter/Execute.cs, BHoM_UI/Components/Adapter/Move.cs, BHoM_UI/Components/Adapter/Pull.cs, BHoM_UI/Components/Adapter/Push.cs, BHoM_UI/Components/Adapter/Remove.cs, BHoM_UI/Components/oM/CreateObject.cs, BHoM_UI/Global/SearchMenu.cs, BHoM_UI/Templates/Caller.cs, BHoM_UI/packages.config, UI_oM/ParamOldIndexFragment.cs, UI_oM/UI_oM.csproj
https://github.com/BHoM/BHoM_Engine/pull/1371   
https://github.com/BHoM/BHoM_Adapter/pull/164
Closes https://github.com/BHoM/BHoM_UI/issues/171
Closes https://github.com/BHoM/BHoM_UI/issues/166
- Added PushType/PullType to the respective method inputs
- Delete action renamed to Remove
- Adapter actions now accepts IRequest 
- General tidy up of UI methods for adapter actions
=> Aligning with changes in BHoMAdapter Refactoring Level 04

.ci/run-compliance-tests.yml
Fixes #194 
If the ticks are green it's good to go
=> Update CI files

UI_oM/ParamOldIndexFragment.cs
https://github.com/BHoM/BHoM/pull/711
https://github.com/BHoM/BHoM_Engine/pull/1495
Fixes #208
=> Rename IBHoMFragment -> IFragment

BHoM_UI/Components/Engine/SetProperty.cs
=> Fix casting error on input of SetProperty component

BHoM_UI/Components/oM/CreateObject.cs, BHoM_UI/Templates/Caller.cs, BHoM_UI/Templates/MethodCaller.cs
https://github.com/BHoM/BHoM_Engine/pull/1565
Closes https://github.com/BHoM/BHoM_UI/issues/45
This improves significantly support for generic meethods in the UI. See test file for what I have covered. Feel free to list everything that is not yet supported even with this.
This PR doesn't aim at solving all existing problems with generics but to provide a step in the right direction. I have also taken as much precaution as possible to isolate teh code for cases where problems occur with generics. So HOPEFULLY it should brake anything that was previously working. In doubt I would rather merge next quarter.
This takes care of :
- recomputing dynamically input getter when generic input type is not matching
- recomputing dynamically compiled method when generic input types are not matching
- …
=> Improve support to generic types

BHoM_UI/Global/GlobalSearch.cs, UI_Engine/Query/Weight.cs, UI_oM/CustomItem.cs, UI_oM/SearchConfig.cs, UI_oM/UI_oM.csproj
See https://github.com/BHoM/Grasshopper_Toolkit/pull/492 for more details
=> Intellisense for non-BHoM components

BHoM_UI/Templates/Caller.cs
Closes #242
See comment https://github.com/BHoM/BHoM_UI/issues/242#issuecomment-619346538
- @epignatelli , I added you as a reviewer to make sure that I didn't miss anything by changing your original code.
- There is clearly a need to properly list all the possible case of what changes can happen to inputs.outputs and make sure we have a strategy for each. This PR is mainly to patch things up in the mean time.
=> Improve handling of parameters when upgrading a component

BHoM_UI/BHoM_UI.csproj, UI_Engine/UI_Engine.csproj, UI_PostBuild/UI_PostBuild.csproj, UI_oM/UI_oM.csproj
Closes #257
I had to keep the references local for the PostBuid.exe to be able to run properly. I have raised a separate issue to compile it to a different folder than Build.
=> Fix Compliance issue for CSProj files

BHoM_UI/Components/Engine/Explode.cs
Closes #191 
Explode now give a description of the properties **_IF_** there is a single type of objects provided as input. I separated that case of a single type from the others to make it clearer in the code.
Just try a few explodes on different objects
- I am aware that if you do something like explode `Point` and then change the input type to `Vector`, the description is not going to change because they have the exact same list of properties (and same names). This can only be fixed in each UI. Keep in mind that this is very rare since it needs the exact same properties.
- I am not too happy with the increase of code complexity (number of ifs) but I don't think it can be avoided without a much larger refactoring. This is due to Dictionaries and custom objects being exceptional cases.
=> Explode to give descriptions of properties

UI_Engine/Query/Items.cs
Closes #301
Just make sure that the menu of the CreateRequest component only allows to produce `IRequest`
=> Fix list of possible items in CreateRequest component

BHoM_UI/Caller/Run.cs, BHoM_UI/Components/Adapter/Execute.cs, BHoM_UI/Components/Adapter/Move.cs, BHoM_UI/Components/Adapter/Pull.cs, BHoM_UI/Components/Adapter/Push.cs, BHoM_UI/Components/Adapter/Remove.cs
=> Make sure success output is false when active is false on adater components

BHoM_UI/Components/Adapter/Execute.cs, BHoM_UI/Components/Adapter/Move.cs, BHoM_UI/Components/Adapter/Pull.cs, BHoM_UI/Components/Adapter/Push.cs, BHoM_UI/Components/Adapter/Remove.cs
https://github.com/BHoM/BHoM_Adapter/pull/264
Closes https://github.com/BHoM/BHoM_UI/issues/317
See the issue and the description in https://github.com/BHoM/BHoM_Adapter/pull/264#issue-513090325 for more info.
I need this quite urgently now because of some needed changes in other toolkits (File_Adapter).
=> Removed the setup logic of the Adapter Actions

BHoM_UI/BHoM_UI.csproj
https://github.com/BHoM/BHoM/pull/1068
https://github.com/BHoM/BHoM_Engine/pull/2132
Closes https://github.com/BHoM/BHoM/issues/1067
See https://github.com/BHoM/BHoM_Engine/pull/2132.
- code updated to the changes made in https://github.com/BHoM/BHoM/pull/1068
Both this PR and #331 modify the same file, but GitHub should be able to deal with rebasing both (at least I believe so 🙊). However, if you are afraid that will not be the case @adecler, then let's merge #331 first, regardless of which one is ready sooner.
=> Code updated to the changes introduced in BHoM #1068 (references updated)

BHoM_UI/Caller/Run.cs
https://github.com/BHoM/BHoM_Engine/pull/2218
Closes #338
This is a temporary fix on the bug related to handling generic method components. That fix is fairly close to the final solution but will be improved once we have completed the new version of the event log system. 
See file provided in the issue
=> Fix input handling error on component using generic methods

.ci/code/UI_Test/Helpers/InstantiateCaller.cs, .ci/code/UI_Test/Helpers/PossibleComponentItems.cs, .ci/code/UI_Test/Objects/DummyAccessor.cs, .ci/code/UI_Test/Objects/DummyCaller.cs, .ci/code/UI_Test/Properties/AssemblyInfo.cs, .ci/code/UI_Test/UI_Test.csproj, .ci/code/UI_Test/Verify/ComponentInstantiation.cs, .ci/code/UI_Test/Verify/ComponentReadWriteCycle.cs, .ci/code/UI_Test/Verify/ComponentRunCycle.cs, .ci/code/Verification.sln
https://github.com/BHoM/BHoM_Engine/pull/2251
https://github.com/BHoM/Test_Toolkit/pull/311
Closes #347 
This provides 3 series of tests:
- Make sure that all items available from the components' menu can be used to generate a valid component
- Test if all the possible components in the BHoM can be copied/saved without error
- Check that all parameters (input/output) are handled correctly without error. This uses a dummy component that behaves exactly like the other to the difference that it doesn't run the selected item and generates dummy outputs of the expected types instead. 
Use the `TestRunner` with the `UI` argument
=> Add test scripts for core UI

BHoM_UI/Components/UI/UnitTest.cs
=> Ensure immutability of inputs to Unit Test component

BHoM_UI/Components/Engine/Modify.cs
Closes #360
See issue.
Not many Modify methods returning `void` right now but I tested it successfully on this:
I suggest you either test it on some "hand-made` Modify methods or some that you are familiar with.
=> Handling of Modify methods returning void

BHoM_UI/Components/Adapter/Move.cs
Closes #266
Should be pretty straightforward. Let me know if you disagree 😄
=> Fix typo in Move component

BHoM_UI/Components/Engine/SetProperty.cs
Closes #365
[SharePoint](https://burohappold.sharepoint.com/:f:/s/BHoM/EuleqCwV7x1Gl_Rr0G9o2F4B526jGj-nMrGDdw0ihZXvOQ?e=kexUYA)
It is worth noting that something like `bar.SectionProperty.Reinforcement` would not actually compile in C# because `SectionProperty` of a `Bar` is an `ISectionProperty`. That interface doesn't have a `Reinforcement` property. So technically, there is an argument for returning an error when trying to execute the same in Grasshopper. Since there is however a workaround to give the users what they need, I think it is better to do so.
=> Fix SetProperty for list nested properties

BHoM_UI/Components/Engine/SetProperty.cs
Closes #375
Fix the case where the user try to set a property of object inside a list property. Example: setting the property `Layers.Material` of a `Construction`.
This also added a fallback object type for case where the user is trying to set properties in the CustomData for example. 
Use the one provided in the issue.
I have also added some additional check where the List property is not following an interface property just to be sure (as those two scenarios are treated slightly differently).
I would recommend also testing anything that comes to mind or existing files as it seems there are still cases I don't think about (as this PR proves). I have, for example, re-tested the file from this PR: https://github.com/BHoM/BHoM_UI/pull/371
=> Fix Property access type for specific case of accessing Object.List.Property

BHoM_UI/Caller/Run.cs
https://github.com/BHoM/BHoM_Engine/pull/2367
See https://github.com/BHoM/BHoM_Engine/pull/2367
=> Make sure that IEnumerable of generics are handled properly

UI_Engine/Query/Items.cs
Closes #391 
See issue
Just try to create a `DateTime` type from the `CreateType` component and make sure that it works
=> Add ability to create a DateTime type from the CreateType component

BHoM_UI/Global/GlobalSearch.cs
=> Replace calls to GetShallowClone

UI_Engine/Query/Items.cs
https://github.com/BHoM/BHoM_Engine/pull/2681
Closes #
See https://github.com/BHoM/BHoM_Engine/pull/2681 - as for this PR, if it compiles, all is fine.
=> Code alignment to the changes done in BHoM_Engine #2681

BHoM_UI/Caller/Read.cs, BHoM_UI/Components/oM/CreateData.cs
https://github.com/BHoM/BHoM_Engine/pull/2845
Adds support for versioning of Datasets by calling the ValidatePath method in the Library_Engine
See link in Engine PR
=> Add support for versioning of Datasets

.ci/code/UI_Test/Helpers/InstantiateCaller.cs, .ci/code/UI_Test/Helpers/PossibleComponentItems.cs, .ci/code/UI_Test/Objects/DummyAccessor.cs, .ci/code/UI_Test/UI_Test.csproj, .ci/code/UI_Test/Verify/ComponentInstantiation.cs, .ci/code/UI_Test/Verify/ComponentReadWriteCycle.cs, .ci/code/UI_Test/Verify/ComponentRunCycle.cs
Updates usings in the CI verification code following the Reflection changes.
=> Update Reflection -> Base on CI verification code

BHoM_UI/BHoM_UI.csproj, UI_Engine/Compute/LogUsage.cs, UI_oM/ProjectIDEvent.cs, UI_oM/TriggerLogUsageArgs.cs, UI_oM/UI_oM.csproj
Fixes #428 - don't read the issue thread though 🤕 
Fixes #426 - not in the way the issue describes but in a suitable way for the desires of the workflows
=> Add file ID to trigger of usage args

BHoM_UI/CallerTemplates/MultiChoiceCaller.cs, BHoM_UI/Menus/ItemSelectorMenu_WinForm.cs
Closes #449
Try creating and navigating dropdowns (enums, datasets) - search bar should be available under right click now.
=> Search in dropdowns unlocked

UI_Engine/Query/Information.cs
Closes #458 
-constant strings changed to call DocumentationURL and BHoMWebsiteURL.
=> Updated URL to method calls

.ci/BHoMBot/Nuget/BHoM.UI.nuspec
=> Add nuspec template file

BHoM_UI/BHoM_UI.csproj, BHoM_UI/Global/Initialisation.cs
=> Load settings on loading of UI

BHoM_UI/Components/Adapter/Execute.cs, BHoM_UI/Components/Adapter/Move.cs, BHoM_UI/Components/Adapter/Pull.cs, BHoM_UI/Components/Adapter/Push.cs, BHoM_UI/Components/Adapter/Remove.cs
https://github.com/BHoM/BHoM_Adapter/pull/384
=> Add calls to the before/after actions added in BHoM_Adapter

.ci/code/UI_Test/Properties/AssemblyInfo.cs, BHoM_UI/Properties/AssemblyInfo.cs, BHoM_Windows_UI/Properties/AssemblyInfo.cs, UI_Engine/Properties/AssemblyInfo.cs, UI_oM/Properties/AssemblyInfo.cs
Update AssemblyFileVersion to 7.3
Remove previous version attributes
=> Update AssemblyFileVersion to 7.3

UI_Engine/Compute/CheckLogOnUiEndOpening.cs, UI_Engine/Compute/Constructor.cs, UI_Engine/Compute/ConstructorText.cs, UI_Engine/Compute/InputAccessor.cs, UI_Engine/Compute/LoadAssemblies.cs, UI_Engine/Compute/LogUsage.cs, UI_Engine/Compute/Organise.cs, UI_Engine/Compute/OutputAccessor.cs, UI_Engine/Compute/RecordError.cs, UI_Engine/Compute/RecordExecutionError.cs, UI_Engine/Compute/SaveSettings.cs, UI_Engine/Compute/UpdateProjectId.cs, UI_Engine/Create/ParamInfo.cs, UI_Engine/Objects/DocumentLoading.cs, UI_Engine/Query/AreMatching.cs, UI_Engine/Query/Changes.cs, UI_Engine/Query/Depth.cs, UI_Engine/Query/Hits.cs, UI_Engine/Query/MatchWith.cs, UI_Engine/Query/OutputParams.cs, UI_Engine/Query/SelectionIndex.cs, UI_Engine/Query/SubType.cs, UI_Engine/Query/ToText.cs, UI_Engine/Query/Weight.cs, UI_Engine/Versioning_83.json
Closes #527
The documentation compliance check should pass
=> Fix documentation compliance in UI_Engine
